apiVersion: apps/v1
kind: Deployment
metadata:
  name: actual-budget
  namespace: actual-budget-production
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: actual-budget
  template:
    metadata:
      labels:
        app: actual-budget
    spec:
      containers:
        - name: actual-budget
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 5006
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: actual-budget
  namespace: actual-budget-production
spec:
  selector:
    app: actual-budget
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5006
  externalIPs:
    - {{ .Values.service.externalIP }}
