apiVersion: v1
kind: Namespace
metadata:
  name: actual-budget
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-data-pvc
  namespace: actual-budget
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actual-budget
  namespace: actual-budget
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actual-budget
  template:
    metadata:
      labels:
        app: actual-budget
    spec:
      containers:
      - name: actual-budget
        image: actualbudget/actual-server:latest
        ports:
        - containerPort: 5006
        volumeMounts:
        - name: actual-data
          mountPath: /data
      volumes:
      - name: actual-data
        persistentVolumeClaim:
          claimName: actual-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: actual-budget
  namespace: actual-budget
spec:
  type: ClusterIP
  selector:
    app: actual-budget
  ports:
  - port: 8082
    targetPort: 5006
  externalIPs:
  - 10.56.1.164
