all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: /work/.ssh/id_rsa
  hosts:
    node1:
      ansible_host: 129.114.26.190
      ansible_user: cc
    node2:
      ansible_host: 192.168.1.12
      ansible_user: cc
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyJump=cc@129.114.26.190'
    node3:
      ansible_host: 192.168.1.13
      ansible_user: cc
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyJump=cc@129.114.26.190'
